export interface PhysicsConfig {
  sensitivity: number;
  friction: number;
  deadzone: number;
  startingLives: number;
}

export const DEFAULT_CONFIG: Readonly<PhysicsConfig> = {
  sensitivity: 0.05,
  friction: 0.85,
  deadzone: 0.5,
  startingLives: 3,
};

export function exportConfigH(cfg: PhysicsConfig): string {
  return [
    "// Generated by MazeDev HUD – paste over the physics section of packages/firmware/src/config.h",
    "",
    `constexpr float SENSITIVITY    = ${cfg.sensitivity.toFixed(3)}f;`,
    `constexpr float FRICTION       = ${cfg.friction.toFixed(3)}f;`,
    `constexpr float DEADZONE       = ${cfg.deadzone.toFixed(3)}f;`,
    `constexpr int   STARTING_LIVES = ${cfg.startingLives};`,
  ].join("\n");
}
